[package]
name = "jonla-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jonla-parser = { path = "../jonla-parser" }
rpds = "0.12.0"
by_address = "1.1.0"